-- Please use the Localization App on WoWAce to Update this
-- https://wow.curseforge.com/projects/wowgatheringnodes/localization

local debug = false
--@debug@
debug = true
--@end-debug@

local WoWGatheringNodes = LibStub("AceAddon-3.0"):NewAddon("WoWGatheringNodes")
local L = LibStub("AceLocale-3.0"):NewLocale("WoWGatheringNodes", "enUS", true, debug)
if not L then return end

--@localization(locale="enUS", format="lua_additive_table")@

--@do-not-package@ 
L["Clear Data"] = "Clear Data"
L["Clears data from memory if version has already been imported."] = "Clears data from memory if version has already been imported."
L["Custom Objects"] = "Custom Objects"
L["Enable Custom Objects"] = "Enable Custom Objects"
L["Failed to load WoWGatheringNodes due to "] = "Failed to load WoWGatheringNodes due to "
L["Import WoWGatheringNodes"] = "Import WoWGatheringNodes"
L["Inject %s into gathering addons"] = "Inject %s into gathering addons"
L["Injects new objects into Gatherer/Gathermate2 that are not currently in their data files"] = "Injects new objects into Gatherer/Gathermate2 that are not currently in their data files"
L["Load WoWGatheringNodes and import the data to your database."] = "Load WoWGatheringNodes and import the data to your database."
L["Merge will add WoWGatheringNodes to your database. Overwrite will replace your database with the data in WoWGatheringNodes"] = "Merge will add WoWGatheringNodes to your database. Overwrite will replace your database with the data in WoWGatheringNodes"
L["WoWGatheringNodes has been imported."] = "WoWGatheringNodes has been imported."
L["Auto Import New Data"] = "Auto Import New Data"
L["Automaticaly imports data when updated data is found"] = "Automaticaly imports data when updated data is found"
L["Auto Import to Herb Data to Carbonite"] = "Auto Import to Herb Data to Carbonite"
L["Auto Import to Mine Data to Carbonite"] = "Auto Import to Mine Data to Carbonite"
L["Auto Import to Data Gathermate"] = "Auto Import Data to Gathermate"
 --@end-do-not-package@
WoWGatheringNodes.NodeIdNames = {}

WoWGatheringNodes.NodeIdNames[2047] =  "Truesilver Deposit"
WoWGatheringNodes.NodeIdNames[3729] =  "Briarthorn"
WoWGatheringNodes.NodeIdNames[181109] =  "Gold Vein"
WoWGatheringNodes.NodeIdNames[103711] =  "Tin Vein"
WoWGatheringNodes.NodeIdNames[1619] =  "Earthroot"
WoWGatheringNodes.NodeIdNames[1667] =  "Incendicite Mineral Vein"
WoWGatheringNodes.NodeIdNames[123309] =  "Ooze Covered Truesilver Deposit"
WoWGatheringNodes.NodeIdNames[3763] =  "Copper Vein"
WoWGatheringNodes.NodeIdNames[1731] =  "Copper Vein"
WoWGatheringNodes.NodeIdNames[176189] =  "Skeletal Sea Turtle"
WoWGatheringNodes.NodeIdNames[3764] =  "Tin Vein"
WoWGatheringNodes.NodeIdNames[2653] =  "Lesser Bloodstone Deposit"
WoWGatheringNodes.NodeIdNames[103712] =  "Iron Deposit"
WoWGatheringNodes.NodeIdNames[1621] =  "Briarthorn"
WoWGatheringNodes.NodeIdNames[176587] =  "Plaguebloom"
WoWGatheringNodes.NodeIdNames[123310] =  "Ooze Covered Mithril Deposit"
WoWGatheringNodes.NodeIdNames[141853] =  "Violet Tragan"
WoWGatheringNodes.NodeIdNames[1733] =  "Silver Vein"
WoWGatheringNodes.NodeIdNames[73939] =  "Ooze Covered Iron Deposit"
WoWGatheringNodes.NodeIdNames[176588] =  "Icecap"
WoWGatheringNodes.NodeIdNames[175207] =  "Beached Sea Creature"
WoWGatheringNodes.NodeIdNames[2054] =  "Tin Vein"
WoWGatheringNodes.NodeIdNames[176636] =  "Sungrass"
WoWGatheringNodes.NodeIdNames[1734] =  "Gold Vein"
WoWGatheringNodes.NodeIdNames[180510] =  "Solanian's Scrying Orb"
WoWGatheringNodes.NodeIdNames[176589] =  "Black Lotus"
WoWGatheringNodes.NodeIdNames[176637] =  "Gromsblood"
WoWGatheringNodes.NodeIdNames[1735] =  "Iron Deposit"
WoWGatheringNodes.NodeIdNames[180511] =  "Scroll of Scourge Magic"
WoWGatheringNodes.NodeIdNames[150079] =  "Mithril Deposit"
WoWGatheringNodes.NodeIdNames[176638] =  "Golden Sansam"
WoWGatheringNodes.NodeIdNames[103714] =  "Copper Vein"
WoWGatheringNodes.NodeIdNames[180512] =  "Solanian's Journal"
WoWGatheringNodes.NodeIdNames[323] =  "Arcanite Lode"
WoWGatheringNodes.NodeIdNames[150080] =  "Gold Vein"
WoWGatheringNodes.NodeIdNames[176639] =  "Dreamfoil"
WoWGatheringNodes.NodeIdNames[1610] =  "Incendicite Mineral Vein"
WoWGatheringNodes.NodeIdNames[73941] =  "Ooze Covered Gold Vein"
WoWGatheringNodes.NodeIdNames[150081] =  "Truesilver Deposit"
WoWGatheringNodes.NodeIdNames[176640] =  "Mountain Silversage"
WoWGatheringNodes.NodeIdNames[142142] =  "Sungrass"
WoWGatheringNodes.NodeIdNames[176586] =  "Mountain Silversage"
WoWGatheringNodes.NodeIdNames[252] =  "I Should not be here B"
WoWGatheringNodes.NodeIdNames[181068] =  "Small Obsidian Chunk"
WoWGatheringNodes.NodeIdNames[123848] =  "Ooze Covered Thorium Vein"
WoWGatheringNodes.NodeIdNames[2040] =  "Mithril Deposit"
WoWGatheringNodes.NodeIdNames[150082] =  "Small Thorium Vein"
WoWGatheringNodes.NodeIdNames[176641] =  "Plaguebloom"
WoWGatheringNodes.NodeIdNames[142144] =  "Ghost Mushroom"
WoWGatheringNodes.NodeIdNames[142143] =  "Blindweed"
WoWGatheringNodes.NodeIdNames[142145] =  "Gromsblood"
WoWGatheringNodes.NodeIdNames[1628] =  "Grave Moss"
WoWGatheringNodes.NodeIdNames[142141] =  "Arthas' Tears"
WoWGatheringNodes.NodeIdNames[2041] =  "Liferoot"
WoWGatheringNodes.NodeIdNames[176753] =  "Doom Weed"
WoWGatheringNodes.NodeIdNames[176642] =  "Arthas' Tears"
WoWGatheringNodes.NodeIdNames[142140] =  "Purple Lotus"
WoWGatheringNodes.NodeIdNames[175404] =  "Rich Thorium Vein"
WoWGatheringNodes.NodeIdNames[175928] =  "Incendia Agave"
WoWGatheringNodes.NodeIdNames[2866] =  "Firebloom"
WoWGatheringNodes.NodeIdNames[2044] =  "Wintersbite"
WoWGatheringNodes.NodeIdNames[324] =  "Small Thorium Vein"
WoWGatheringNodes.NodeIdNames[1622] =  "Bruiseweed"
WoWGatheringNodes.NodeIdNames[176643] =  "Small Thorium Vein"
WoWGatheringNodes.NodeIdNames[1732] =  "Tin Vein"
WoWGatheringNodes.NodeIdNames[2042] =  "Fadeleaf"
WoWGatheringNodes.NodeIdNames[1624] =  "Kingsblood"
WoWGatheringNodes.NodeIdNames[165658] =  "Dark Iron Deposit"
WoWGatheringNodes.NodeIdNames[1623] =  "Wild Steelbloom"
WoWGatheringNodes.NodeIdNames[2043] =  "Khadgar's Whisker"
WoWGatheringNodes.NodeIdNames[3730] =  "Bruiseweed"
WoWGatheringNodes.NodeIdNames[176644] =  "Rich Thorium Vein"
WoWGatheringNodes.NodeIdNames[73940] =  "Ooze Covered Silver Vein"
WoWGatheringNodes.NodeIdNames[103709] =  "Tin Vein"
WoWGatheringNodes.NodeIdNames[1620] =  "Mageroyal"
WoWGatheringNodes.NodeIdNames[3727] =  "Mageroyal"
WoWGatheringNodes.NodeIdNames[3726] =  "Earthroot"
WoWGatheringNodes.NodeIdNames[13874] =  "Serpentbloom"
WoWGatheringNodes.NodeIdNames[105569] =  "Silver Vein"
WoWGatheringNodes.NodeIdNames[176645] =  "Mithril Deposit"
WoWGatheringNodes.NodeIdNames[177388] =  "Ooze Covered Rich Thorium Vein"
WoWGatheringNodes.NodeIdNames[13891] =  "Serpentbloom"
WoWGatheringNodes.NodeIdNames[3724] =  "Peacebloom"
WoWGatheringNodes.NodeIdNames[175566] =  "Gloom Weed"
WoWGatheringNodes.NodeIdNames[35253] =  "Mining Node Point Check"
WoWGatheringNodes.NodeIdNames[2045] =  "Stranglekelp"
WoWGatheringNodes.NodeIdNames[3725] =  "Silverleaf"
WoWGatheringNodes.NodeIdNames[103713] =  "Copper Vein"
WoWGatheringNodes.NodeIdNames[180600] =  "Unstable Mana Crystal Crate"
WoWGatheringNodes.NodeIdNames[103710] =  "Iron Deposit"
WoWGatheringNodes.NodeIdNames[1617] =  "Silverleaf"
WoWGatheringNodes.NodeIdNames[176583] =  "Golden Sansam"
WoWGatheringNodes.NodeIdNames[19903] =  "Indurium Mineral Vein"
WoWGatheringNodes.NodeIdNames[2046] =  "Goldthorn"
WoWGatheringNodes.NodeIdNames[123308] =  "Ooze Covered Arcanite Lode"
WoWGatheringNodes.NodeIdNames[2055] =  "Copper Vein"
WoWGatheringNodes.NodeIdNames[181108] =  "Truesilver Deposit"
WoWGatheringNodes.NodeIdNames[35254] =  "Herb Node Point Check"
WoWGatheringNodes.NodeIdNames[1618] =  "Peacebloom"
WoWGatheringNodes.NodeIdNames[176584] =  "Dreamfoil"
WoWGatheringNodes.NodeIdNames[181069] =  "Large Obsidian Chunk"
